diasdevida=int(input())
anos = int(diasdevida/365)
meses = int((diasdevida - 365*anos) / 30)
dias = int(diasdevida - 365*anos - 30*meses)
print (f'{anos} ano(s)')
print(f'{meses} mes(es)')
print(f'{dias} dia(s)')
